name: file-upload-service-ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install Dependencies
        run: |
          pip install -r requirements-dev.txt
          pip install -r requirements.txt
      - name: Run Ruff
        run: ruff check .
